---
title: "cross_validation"
author: "Juliet Rowe"
date: "2023-11-09"
output: html_document
---

## Load key packages

```{r}
library(tidyverse)
library(modelr)
library(p8105.datasets)

set.seed(1)
```


## Nonlinear data and CV

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x=runif(100, 0, 1),
    y = 1-10*(x-0.3)^2 + rnorm(100, 0, 0.3)
  )

nonlin_df |>
  ggplot(aes(x=x, y=y)) + geom_point()
```

Do the train/test split

```{r}
train_df = sample_n(nonlin_df, 80)

test_df = anti_join(nonlin_df, train_df, by="id")
```

```{r}
ggplot(train_df, aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```


```{r}
linear_mod = lm(y~x, data=train_df)
smooth_mod = mgcv::gam(y~s(x), data=train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

Quick visualization of linear model
```{r}
train_df |>
  modelr::add_predictions(smooth_mod) |>
  ggplot(aes(x=x, y=y)) + geom_point() + geom_line(aes(y=pred))
```

RMSEs on training data can be misleading...
```{r}
rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(wiggly_mod, train_df)

```

RMSEs on testing data gives a sense of out-of-sample prediction accuracy!
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```


##Use modelr for CV

```{r}
cv_df = 
  nonlin_df |>
  crossv_mc(n=100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```


```{r}
cv_df |> pull(train) |> nth(1) |> as_tibble()
```


Apply each model to all training datasets, and evaluate on all testing datasets

```{r}
cv_results = 
  cv_df |> 
  mutate(
    linear_fit  = map(train, ~lm(y ~ x, data = .x)),
    smooth_fit  = map(train, ~mgcv::gam(y ~ s(x), data = .x)),
    wiggly_fit  = map(train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))) |> 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, ~rmse(model = .x, data = .y)))
```

```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

